// Type definitions for spells and skills

export type SpellName =
  // 1st circle
  | 'clumsy'
  | 'create food'
  | 'feeblemind'
  | 'heal'
  | 'magic arrow'
  | 'night sight'
  | 'reactive armor'
  | 'weaken'
  // 2nd circle
  | 'agility'
  | 'cunning'
  | 'cure'
  | 'harm'
  | 'magic trap'
  | 'magic untrap'
  | 'protection'
  | 'strength'
  // 3rd circle
  | 'bless'
  | 'fireball'
  | 'magic lock'
  | 'poison'
  | 'telekinesis'
  | 'teleport'
  | 'unlock'
  | 'wall of stone'
  // 4th circle
  | 'arch cure'
  | 'arch protection'
  | 'curse'
  | 'fire field'
  | 'greater heal'
  | 'lightning'
  | 'mana drain'
  | 'recall'
  // 5th circle
  | 'blade spirit'
  | 'dispel field'
  | 'incognito'
  | 'magic reflection'
  | 'spell reflection'
  | 'mind blast'
  | 'paralyze'
  | 'poison field'
  | 'summon creature'
  // 6th circle
  | 'dispel'
  | 'energy bolt'
  | 'explosion'
  | 'invisibility'
  | 'mark'
  | 'mass curse'
  | 'paralyze field'
  | 'reveal'
  // 7th circle
  | 'chain lightning'
  | 'energy field'
  | 'flame strike'
  | 'gate travel'
  | 'mana vampire'
  | 'mass dispel'
  | 'meteor swarm'
  | 'polymorph'
  // 8th circle
  | 'earthquake'
  | 'energy vortex'
  | 'resurrection'
  | 'summon air elemental'
  | 'summon daemon'
  | 'summon earth elemental'
  | 'summon fire elemental'
  | 'summon water elemental'
  // Necromancy
  | 'animate dead'
  | 'blood oath'
  | 'corpse skin'
  | 'curse weapon'
  | 'evil omen'
  | 'horrific beast'
  | 'lich form'
  | 'mind rot'
  | 'pain spike'
  | 'poison strike'
  | 'strangle'
  | 'summon familiar'
  | 'vampiric embrace'
  | 'vengeful spirit'
  | 'wither'
  | 'wraith form'
  | 'exorcism'
  // Paladin spells
  | 'cleanse by fire'
  | 'close wounds'
  | 'consecrate weapon'
  | 'dispel evil'
  | 'divine fury'
  | 'enemy of one'
  | 'holy light'
  | 'noble sacrifice'
  | 'remove curse'
  | 'sacred journey'
  // Bushido
  | 'confidence'
  | 'counter attack'
  | 'evasion'
  | 'honorable execution'
  | 'lightning strike'
  | 'momentum strike'
  // Ninjitsu
  | 'animal form'
  | 'backstab'
  | 'death strike'
  | 'focus attack'
  | 'ki attack'
  | 'mirror image'
  | 'shadow jump'
  | 'surprise attack'
  // Spellweaving
  | 'arcane circle'
  | 'arcane empowerment'
  | 'attune weapon'
  | 'dryad allure'
  | 'essence of wind'
  | 'ethereal voyage'
  | 'gift of life'
  | 'gift of renewal'
  | 'immolating weapon'
  | 'mana phantasm'
  | 'nature\'s fury'
  | 'reaper form'
  | 'rising colossus'
  | 'soul seeker'
  | 'summon fey'
  | 'summon fiend'
  | 'thunderstorm'
  | 'wildfire'
  | 'word of death'
  // Mysticism
  | 'animated weapon'
  | 'bombard'
  | 'cleansing winds'
  | 'eagle strike'
  | 'enchant'
  | 'healing stone'
  | 'hail storm'
  | 'mass sleep'
  | 'nether bolt'
  | 'purge magic'
  | 'rising colossus'
  | 'sleep'
  | 'spell plague'
  | 'stone form'
  | 'spell trigger'
  | 'spellweaving';

export type SkillName =
  // Combat
  | 'alchemy'
  | 'anatomy'
  | 'archery'
  | 'arms lore'
  | 'fencing'
  | 'healing'
  | 'mace fighting'
  | 'parrying'
  | 'swordsmanship'
  | 'tactics'
  | 'wrestling'
  // Magic
  | 'magery'
  | 'necromancy'
  | 'chivalry'
  | 'bushido'
  | 'ninjitsu'
  | 'spellweaving'
  | 'mysticism'
  | 'evaluating intelligence'
  | 'meditation'
  | 'resisting spells'
  | 'spirit speak'
  // Bard
  | 'discordance'
  | 'musicianship'
  | 'peacemaking'
  | 'provocation'
  // Crafting
  | 'blacksmithy'
  | 'bowcraft'
  | 'fletching'
  | 'carpentry'
  | 'cooking'
  | 'inscription'
  | 'tailoring'
  | 'tinkering'
  | 'imbuing'
  | 'glassblowing'
  | 'masonry'
  // Wilderness
  | 'animal lore'
  | 'animal taming'
  | 'camping'
  | 'fishing'
  | 'herding'
  | 'lumberjacking'
  | 'mining'
  | 'tracking'
  | 'veterinary'
  // Thief
  | 'detect hidden'
  | 'hiding'
  | 'lockpicking'
  | 'poisoning'
  | 'remove trap'
  | 'snooping'
  | 'stealing'
  | 'stealth'
  // Miscellaneous
  | 'begging'
  | 'cartography'
  | 'focus'
  | 'forensic evaluation'
  | 'item identification'
  | 'taste identification'
  | 'throwing';

