// All constants used in js_stealth
// Consolidates LAYERS, DIRECTIONS, NOTORIETY, SPELLS, and other game constants

// Layer constants (from py_stealth methods.py)
export const LAYERS = {
  Rhand: 0x01,
  Lhand: 0x02,
  Shoes: 0x03,
  Pants: 0x04,
  Shirt: 0x05,
  Hat: 0x06,
  Gloves: 0x07,
  Ring: 0x08,
  Talisman: 0x09,
  Neck: 0x0A,
  Hair: 0x0B,
  Waist: 0x0C,
  Torso: 0x0D,
  Brace: 0x0E,
  Beard: 0x10,
  TorsoH: 0x11,
  Ear: 0x12,
  Arms: 0x13,
  Cloak: 0x14,
  Bpack: 0x15,
  Robe: 0x16,
  Eggs: 0x17,
  Legs: 0x18,
  Horse: 0x19,
  Rstk: 0x1A,
  NRstk: 0x1B,
  Sell: 0x1C,
  Bank: 0x1D,
} as const;

export type Layer = typeof LAYERS[keyof typeof LAYERS];

// Direction constants (from CalcDir in py_stealth)
export const DIRECTIONS = {
  North: 0,
  Northeast: 1,
  East: 2,
  Southeast: 3,
  South: 4,
  Southwest: 5,
  West: 6,
  Northwest: 7,
} as const;

export type Direction = keyof typeof DIRECTIONS;
export type DirectionValue = typeof DIRECTIONS[keyof typeof DIRECTIONS];

// Notoriety constants (from UO standard)
export const NOTORIETY = {
  Innocent: 1,      // Blue
  Ally: 2,          // Green
  Attackable: 3,    // Grey
  Criminal: 4,      // Grey
  Enemy: 5,         // Orange/Red
  Murderer: 6,      // Red
  Invulnerable: 7,  // Yellow
} as const;

export type Notoriety = typeof NOTORIETY[keyof typeof NOTORIETY];

// Spell names mapped to IDs (from py_stealth)
export const SPELLS = {
  // 1st circle
  'clumsy': 1,
  'create food': 2,
  'feeblemind': 3,
  'heal': 4,
  'magic arrow': 5,
  'night sight': 6,
  'reactive armor': 7,
  'weaken': 8,
  // 2nd circle
  'agility': 9,
  'cunning': 10,
  'cure': 11,
  'harm': 12,
  'magic trap': 13,
  'magic untrap': 14,
  'protection': 15,
  'strength': 16,
  // 3rd circle
  'bless': 17,
  'fireball': 18,
  'magic lock': 19,
  'poison': 20,
  'telekinesis': 21,
  'teleport': 22,
  'unlock': 23,
  'wall of stone': 24,
  // 4th circle
  'arch cure': 25,
  'arch protection': 26,
  'curse': 27,
  'fire field': 28,
  'greater heal': 29,
  'lightning': 30,
  'mana drain': 31,
  'recall': 32,
  // 5th circle
  'blade spirit': 33,
  'dispel field': 34,
  'incognito': 35,
  'magic reflection': 36,
  'spell reflection': 36,
  'mind blast': 37,
  'paralyze': 38,
  'poison field': 39,
  'summon creature': 40,
  // 6th circle
  'dispel': 41,
  'energy bolt': 42,
  'explosion': 43,
  'invisibility': 44,
  'mark': 45,
  'mass curse': 46,
  'paralyze field': 47,
  'reveal': 48,
  // 7th circle
  'chain lightning': 49,
  'energy field': 50,
  'flame strike': 51,
  'gate travel': 52,
  'mana vampire': 53,
  'mass dispel': 54,
  'meteor swarm': 55,
  'polymorph': 56,
  // 8th circle
  'earthquake': 57,
  'energy vortex': 58,
  'resurrection': 59,
  'summon air elemental': 60,
  'summon daemon': 61,
  'summon earth elemental': 62,
  'summon fire elemental': 63,
  'summon water elemental': 64,
  // Necromancy
  'animate dead': 101,
  'blood oath': 102,
  'corpse skin': 103,
  'curse weapon': 104,
  'evil omen': 105,
  'horrific beast': 106,
  'lich form': 107,
  'mind rot': 108,
  'pain spike': 109,
  'poison strike': 110,
  'strangle': 111,
  'summon familiar': 112,
  'vampiric embrace': 113,
  'vengeful spirit': 114,
  'wither': 115,
  'wraith form': 116,
  'exorcism': 117,
  // Paladin spells
  'cleanse by fire': 201,
  'close wounds': 202,
  'consecrate weapon': 203,
  'dispel evil': 204,
  'divine fury': 205,
  'enemy of one': 206,
  'holy light': 207,
  'noble sacrifice': 208,
  'remove curse': 209,
  'sacred journey': 210,
  // Bushido
  'confidence': 401,
  'counter attack': 402,
  'evasion': 403,
  'honorable execution': 404,
  'lightning strike': 405,
  'momentum strike': 406,
  // Ninjitsu
  'animal form': 501,
  'backstab': 502,
  'death strike': 503,
  'focus attack': 504,
  'ki attack': 505,
  'mirror image': 506,
  'shadow jump': 507,
  'surprise attack': 508,
  // Spellweaving
  'arcane circle': 601,
  'arcane empowerment': 602,
  'attune weapon': 603,
  'dryad allure': 604,
  'essence of wind': 605,
  'ethereal voyage': 606,
  'gift of life': 607,
  'gift of renewal': 608,
  'immolating weapon': 609,
  'mana phantasm': 610,
  'nature\'s fury': 611,
  'reaper form': 612,
  'soul seeker': 614,
  'summon fey': 615,
  'summon fiend': 616,
  'thunderstorm': 617,
  'wildfire': 618,
  'word of death': 619,
  // Mysticism
  'animated weapon': 701,
  'bombard': 702,
  'cleansing winds': 703,
  'eagle strike': 704,
  'enchant': 705,
  'healing stone': 706,
  'hail storm': 707,
  'mass sleep': 708,
  'nether bolt': 709,
  'purge magic': 710,
  'rising colossus': 711,
  'sleep': 712,
  'spell plague': 713,
  'stone form': 714,
  'spell trigger': 715,
  'spellweaving': 716,
} as const;

export type SpellName = keyof typeof SPELLS;

// Helper function to get spell ID by name
export function getSpellId(name: string | SpellName): number {
  const lowerName = name.toLowerCase();
  if (!(lowerName in SPELLS)) {
    throw new Error(`Unknown spell name "${name}".`);
  }
  return SPELLS[lowerName as SpellName];
}

// Common skill names (for reference - skills use GetSkillID internally)
// These are the standard UO skill names
export const SKILL_NAMES = [
  'alchemy',
  'anatomy',
  'animal lore',
  'item identification',
  'arms lore',
  'parrying',
  'begging',
  'blacksmithy',
  'bowcraft/fletching',
  'peacemaking',
  'camping',
  'carpentry',
  'cartography',
  'cooking',
  'detecting hidden',
  'discordance',
  'evaluating intelligence',
  'healing',
  'fishing',
  'forensic evaluation',
  'herding',
  'hiding',
  'provocation',
  'inscription',
  'lockpicking',
  'magery',
  'resisting spells',
  'tactics',
  'snooping',
  'musicianship',
  'poisoning',
  'archery',
  'spirit speak',
  'stealing',
  'tailoring',
  'animal taming',
  'taste identification',
  'tinkering',
  'tracking',
  'veterinary',
  'swordsmanship',
  'mace fighting',
  'fencing',
  'wrestling',
  'lumberjacking',
  'mining',
  'meditation',
  'stealth',
  'remove trap',
  'necromancy',
  'focus',
  'chivalry',
  'bushido',
  'ninjitsu',
  'spellweaving',
  'mysticism',
  'imbuing',
  'throwing',
] as const;

export type SkillName = typeof SKILL_NAMES[number];

// Event names (from protocol.ts)
export const EVENTS = [
  'eviteminfo', 'evitemdeleted', 'evspeech', 'evdrawgameplayer',
  'evmoverejection', 'evdrawcontainer', 'evadditemtocontainer',
  'evaddmultipleitemsincont', 'evrejectmoveitem', 'evupdatechar',
  'evdrawobject', 'evmenu', 'evmapmessage', 'evallowrefuseattack',
  'evclilocspeech', 'evclilocspeechaffix', 'evunicodespeech',
  'evbuffdebuffsystem', 'evclientsendresync', 'evcharanimation',
  'evicqdisconnect', 'evicqconnect', 'evicqincomingtext', 'evicqerror',
  'evincominggump', 'evtimer1', 'evtimer2', 'evwindowsmessage', 'evsound',
  'evdeath', 'evquestarrow', 'evpartyinvite', 'evmappin', 'evgumptextentry',
  'evgraphicaleffect', 'evircincomingtext', 'evmessengerevent',
  'evsetglobalvar', 'evupdateobjstats', 'evglobalchat', 'evwardamage',
  'evcontextmenu'
] as const;

export type EventName = typeof EVENTS[number];

// Method indices (from py_stealth methods.py) - comprehensive list
export const METHOD_INDICES = {
  // Basic
  Wait: 0,
  SetEventProc: 7,
  ClearEventProc: 8,
  ProfileName: 11,
  GetConnectedStatus: 12,
  AddToSystemJournal: 13,
  GetSelfID: 14,
  GetX: 15,
  GetY: 16,
  GetZ: 17,
  GetWorldNum: 18,
  GetCharName: 19,
  ChangeProfile: 20,
  GetARStatus: 21,
  SetARStatus: 22,
  GetPauseScriptOnDisconnectStatus: 23,
  SetPauseScriptOnDisconnectStatus: 24,
  GetSelfSex: 25,
  GetCharTitle: 26,
  GetSelfGold: 27,
  GetSelfArmor: 28,
  GetSelfWeight: 29,
  GetSelfMaxWeight: 30,
  GetSelfRace: 31,
  GetSelfPetsMax: 32,
  GetSelfPetsCurrent: 33,
  GetSelfFireResist: 34,
  GetSelfColdResist: 35,
  GetSelfPoisonResist: 36,
  GetSelfEnergyResist: 37,
  GetConnectedTime: 38,
  GetDisconnectedTime: 39,
  GetLastContainer: 40,
  GetLastTarget: 41,
  GetLastAttack: 42,
  GetLastStatus: 43,
  GetLastObject: 44,
  Connect: 45,
  Disconnect: 46,
  GetShardName: 47,
  GetBackpackID: 48,
  // Stats
  GetSelfStr: 49,
  GetSelfInt: 50,
  GetSelfDex: 51,
  GetSelfLife: 52,
  GetSelfMana: 53,
  GetSelfStam: 54,
  GetSelfMaxLife: 55,
  GetSelfMaxMana: 56,
  GetSelfMaxStam: 57,
  GetSelfLuck: 58,
  GetExtInfo: 59,
  GetProxyIP: 60,
  GetProxyPort: 61,
  GetUseProxy: 62,
  GetHiddenStatus: 63,
  GetPoisonedStatus: 64,
  GetParalyzedStatus: 65,
  GetDeadStatus: 66,
  GetWarTargetID: 67,
  SetWarMode: 68,
  Attack: 69,
  UseSelfPaperdollScroll: 70,
  UseOtherPaperdollScroll: 71,
  GetTargetID: 72,
  CancelTarget: 73,
  TargetToObject: 74,
  TargetToXYZ: 75,
  TargetToTile: 76,
  WaitTargetObject: 77,
  WaitTargetTile: 78,
  WaitTargetXYZ: 79,
  WaitTargetSelf: 80,
  WaitTargetType: 81,
  CancelWaitTarget: 82,
  WaitTargetGround: 83,
  WaitTargetLast: 84,
  UsePrimaryAbility: 85,
  UseSecondaryAbility: 86,
  GetAbility: 87,
  ToggleFly: 88,
  GetSkillID: 89,
  UseSkill: 90,
  ChangeSkillLockState: 91,
  GetSkillCap: 92,
  GetSkillValue: 93,
  ReqVirtuesGump: 94,
  UseVirtue: 95,
  CastSpell: 96,
  IsActiveSpellAbility: 98,
  SetCatchBag: 99,
  UnsetCatchBag: 100,
  UseObject: 101,
  UseType: 102,
  UseFromGround: 103,
  ClickOnObject: 104,
  GetFoundedParamID: 105,
  GetLineID: 106,
  GetLineType: 107,
  GetLineTime: 108,
  GetLineMsgType: 109,
  GetLineTextColor: 110,
  GetLineTextFont: 111,
  GetLineIndex: 112,
  GetLineCount: 113,
  GetLineName: 114,
  AddJournalIgnore: 115,
  ClearJournalIgnore: 116,
  AddChatUserIgnore: 117,
  ClearChatUserIgnore: 118,
  ClearJournal: 119,
  LastJournalMessage: 120,
  InJournal: 121,
  InJournalBetweenTimes: 122,
  Journal: 123,
  SetJournalLine: 124,
  LowJournal: 125,
  HighJournal: 126,
  SetFindDistance: 127,
  GetFindDistance: 128,
  SetFindVertical: 129,
  GetFindVertical: 130,
  FindTypeEx: 131,
  FindNotoriety: 132,
  FindAtCoord: 133,
  Ignore: 134,
  IgnoreOff: 135,
  IgnoreReset: 136,
  GetIgnoreList: 137,
  GetFindedList: 138,
  GetFindItem: 139,
  GetFindCount: 140,
  FindQuantity: 141,
  FindFullQuantity: 142,
  PredictedX: 143,
  PredictedY: 144,
  PredictedZ: 145,
  PredictedDirection: 146,
  GetName: 147,
  GetAltName: 148,
  GetTitle: 149,
  GetTooltip: 150,
  GetType: 151,
  GetToolTipRec: 152,
  GetClilocByID: 153,
  GetQuantity: 154,
  IsObjectExists: 155,
  GetPrice: 156,
  GetDirection: 157,
  GetDistance: 158,
  GetColor: 159,
  GetStr: 160,
  GetInt: 161,
  GetDex: 162,
  GetHP: 163,
  GetMaxHP: 164,
  GetMana: 165,
  GetMaxMana: 166,
  GetStam: 167,
  GetMaxStam: 168,
  GetNotoriety: 169,
  GetParent: 170,
  IsWarMode: 171,
  IsNPC: 172,
  IsDead: 173,
  IsRunning: 174,
  IsContainer: 175,
  IsHidden: 176,
  IsMovable: 177,
  IsYellowHits: 178,
  IsPoisoned: 179,
  IsParalyzed: 180,
  IsFemale: 181,
  OpenDoor: 182,
  Bow: 183,
  Salute: 184,
  GetPickupedItem: 185,
  SetPickupedItem: 186,
  GetDropCheckCoord: 187,
  SetDropCheckCoord: 188,
  GetDropDelay: 189,
  SetDropDelay: 190,
  DragItem: 191,
  DropItem: 192,
  RequestContextMenu: 193,
  SetContextMenuHook: 194,
  GetContextMenu: 195,
  ClearContextMenu: 196,
  IsTrade: 197,
  GetTradeContainer: 198,
  GetTradeOpponent: 199,
  TradeCount: 200,
  GetTradeOpponentName: 201,
  TradeCheck: 202,
  ConfirmTrade: 203,
  CancelTrade: 204,
  WaitMenu: 205,
  AutoMenu: 206,
  MenuHookPresent: 207,
  MenuPresent: 208,
  CancelMenu: 209,
  CloseMenu: 210,
  WaitGump: 211,
  WaitTextEntry: 212,
  GumpAutoTextEntry: 213,
  GumpAutoRadiobutton: 214,
  GumpAutoCheckBox: 215,
  NumGumpButton: 216,
  NumGumpTextEntry: 217,
  NumGumpRadiobutton: 218,
  NumGumpCheckBox: 219,
  GetGumpsCount: 220,
  CloseSimpleGump: 221,
  GetGumpSerial: 222,
  GetGumpID: 223,
  IsGumpCanBeClosed: 224,
  GetGumpTextLines: 225,
  GetGumpFullLines: 226,
  GetGumpShortLines: 227,
  GetGumpButtonsDescription: 228,
  GetGumpInfo: 229,
  AddGumpIgnoreByID: 230,
  AddGumpIgnoreBySerial: 231,
  ClearGumpsIgnore: 232,
  ObjAtLayerEx: 233,
  GetLayer: 234,
  WearItem: 235,
  GetDressSpeed: 236,
  SetDressSpeed: 237,
  SetDress: 238,
  EquipDressSet: 239,
  AutoBuy: 240,
  GetShopList: 241,
  ClearShopList: 242,
  AutoBuyEx: 243,
  GetAutoBuyDelay: 244,
  SetAutoBuyDelay: 245,
  GetAutoSellDelay: 246,
  SetAutoSellDelay: 247,
  AutoSell: 248,
  RequestStats: 249,
  HelpRequest: 250,
  QuestRequest: 251,
  RenameMobile: 252,
  MobileCanBeRenamed: 253,
  SetStatState: 254,
  GetStaticArtBitmap: 255,
  PrintScriptMethodsList: 256,
  Alarm: 257,
  HTTP_Get: 258,
  HTTP_Post: 259,
  HTTP_Body: 260,
  HTTP_Header: 261,
  InviteToParty: 262,
  RemoveFromParty: 263,
  PartyMessageTo: 264,
  PartySay: 265,
  PartyCanLootMe: 266,
  PartyAcceptInvite: 267,
  PartyDeclineInvite: 268,
  PartyLeave: 269,
  PartyMembersList: 270,
  InParty: 271,
  ICQConnected: 272,
  ICQConnect: 273,
  ICQDisconnect: 274,
  ICQSetStatus: 275,
  ICQSetXStatus: 276,
  ICQSendText: 277,
  GetTileFlags: 279,
  GetLandTileData: 280,
  GetStaticTileData: 281,
  GetLayerCount: 282,
  ReadStaticsXY: 283,
  GetSurfaceZ: 284,
  IsCellPassable: 285,
  GetStaticsArray: 286,
  GetLandsArray: 287,
  ClientPrint: 289,
  ClientPrintEx: 290,
  CloseClientUIWindow: 291,
  ClientRequestObjectTarget: 292,
  ClientRequestTileTarget: 293,
  ClientTargetResponsePresent: 294,
  ClientTargetResponse: 295,
  CheckLag: 297,
  GetQuestArrow: 300,
  SetSilentMode: 301,
  GetSilentMode: 302,
  FillNewWindow: 303,
  AddToJournal: 304,
  StealthPath: 305,
  GetStealthProfilePath: 306,
  GetShardPath: 307,
  UOSay: 308,
  UOSayColor: 309,
  SetGlobal: 310,
  ConsoleEntryUnicodeReply: 313,
  SetRunUnmountTimer: 316,
  SetWalkMountTimer: 317,
  SetRunMountTimer: 318,
  SetWalkUnmountTimer: 319,
  GetRunMountTimer: 320,
  GetWalkMountTimer: 321,
  GetRunUnmountTimer: 322,
  GetWalkUnmountTimer: 323,
  Step: 324,
  StepQ: 325,
  MoveXYZ: 326,
  MoveXY: 327,
  SetBadLocation: 328,
  SetGoodLocation: 329,
  ClearBadLocationList: 330,
  SetBadObject: 331,
  ClearBadObjectList: 332,
  CheckLOS: 333,
  GetPathArray: 334,
  GetPathArray3D: 335,
  SetFindInNulPoint: 336,
  GetFindInNulPoint: 337,
  GetMenu: 338,
  GetLastMenu: 339,
  FindTypesArrayEx: 340,
  GameServerIPString: 341,
  CloseClientGump: 342,
  ProfileShardName: 343,
  GetLastStepQUsedDoor: 344,
  GetContextMenuRec: 345,
  ClearSystemJournal: 346,
  GetMultis: 347,
  ClearInfoWindow: 348,
  GetBuffBarInfo: 349,
  ConvertIntegerToFlags: 350,
  GetSkillCurrentValue: 351,
  ChangeProfileEx: 352,
  StopMover: 353,
  SetARExtParams: 354,
  GetClientVersionInt: 355,
  UnequipItemsSetMacro: 356,
  EquipItemsSetMacro: 357,
  GetMenuItemsEx: 358,
  UseItemOnMobile: 359,
  BandageSelf: 360,
  GlobalChatJoinChannel: 361,
  GlobalChatLeaveChannel: 362,
  GlobalChatSendMsg: 363,
  GlobalChatActiveChannel: 364,
  GlobalChatChannelsList: 365,
  GetNextStepZ: 367,
  ClientHide: 368,
  GetSkillLockState: 371,
  GetStatLockState: 372,
  IsHouse: 382,
  AddToSystemJournalEx: 386,
  GetStealthInfo: 387,
  GetCell: 388,
  SetMoveOpenDoor: 400,
  GetMoveOpenDoor: 401,
  SetMoveThroughNPC: 402,
  GetMoveThroughNPC: 403,
  SetMoveThroughCorner: 404,
  GetMoveThroughCorner: 405,
  SetMoveHeuristicMult: 406,
  GetMoveHeuristicMult: 407,
  SetMoveCheckStamina: 408,
  GetMoveCheckStamina: 409,
  SetMoveTurnCost: 410,
  GetMoveTurnCost: 411,
  SetMoveBetweenTwoCorners: 412,
  GetMoveBetweenTwoCorners: 413,
  MessengerGetConnected: 501,
  MessengerSetConnected: 502,
  MessengerGetToken: 503,
  MessengerSetToken: 504,
  MessengerGetName: 505,
  MessengerSendMessage: 506,
} as const;

